"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertCircle, CalendarRange, Check, Clock3, LoaderCircle, Pencil, Plus, Target, Trash2, X } from "lucide-react";
import { useAuth } from "@/components/auth/AuthProvider";
import BookCard from "@/components/reading/BookCard";
import BookForm from "@/components/reading/BookForm";
import LucideIcon from "@/components/ui/LucideIcon";
import { Card, SectionHeader } from "@/components/ui/primitives";
import type { ReadingCycle, ReadingProject, ReadingStatus } from "@/data/readingData";
import { completedBooksForCycle, completedBooksForGoal } from "@/data/readingData";
import { currentWeekDates, habitIsScheduled, isoDate } from "@/lib/productivity/date";
import { friendlyProductivityError } from "@/lib/productivity/errors";
import { archiveGoal, archiveReadingProject, archiveTask, clearHabitDayPlan, loadGoals, loadHabitDayPlans, loadHabits, loadReadingData, loadTasks, saveGoal, saveHabitDayPlan, saveReadingCycle, saveReadingProject, saveTask } from "@/lib/productivity/service";
import type { Goal, GoalDraft, Habit, HabitDayPlan, Task, TaskDraft, TaskFrequency } from "@/lib/productivity/types";
import { loadTrainingTemplates } from "@/lib/training/service";
import type { TrainingTemplate } from "@/lib/training/types";

export type PlanningView = "agenda" | "metas" | "biblioteca";
const DOW = ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"];
const FULL_DOW = ["Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"];

export default function PlanningOverview({ view = "agenda" }: { view?: PlanningView }) {
  const { user, loading: authLoading } = useAuth();
  const [habits, setHabits] = useState<Habit[]>([]);
  const [plans, setPlans] = useState<HabitDayPlan[]>([]);
  const [tasks, setTasks] = useState<Task[]>([]);
  const [goals, setGoals] = useState<Goal[]>([]);
  const [trainingTemplates, setTrainingTemplates] = useState<TrainingTemplate[]>([]);
  const [projects, setProjects] = useState<ReadingProject[]>([]);
  const [sessions, setSessions] = useState<Awaited<ReturnType<typeof loadReadingData>>["sessions"]>([]);
  const [cycles, setCycles] = useState<ReadingCycle[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [editingDay, setEditingDay] = useState<string | null>(null);
  const [taskDraft, setTaskDraft] = useState<TaskDraft | null>(null);
  const [goalDraft, setGoalDraft] = useState<GoalDraft | null>(null);
  const [bookDraft, setBookDraft] = useState<ReadingProject | "new" | null>(null);
  const [showCycleForm, setShowCycleForm] = useState(false);
  const dates = useMemo(() => currentWeekDates(), []);

  const refresh = useCallback(async () => {
    if (!user) return;
    const [loadedHabits, loadedPlans, loadedTasks, loadedGoals, loadedTemplates, reading] = await Promise.all([
      loadHabits(user.id), loadHabitDayPlans(user.id, dates[0], dates[6]), loadTasks(user.id), loadGoals(user.id), loadTrainingTemplates(user.id), loadReadingData(user.id),
    ]);
    setHabits(loadedHabits); setPlans(loadedPlans); setTasks(loadedTasks); setGoals(loadedGoals); setTrainingTemplates(loadedTemplates);
    setProjects(reading.projects); setSessions(reading.sessions); setCycles(reading.cycles);
  }, [dates, user]);

  useEffect(() => {
    if (authLoading) return;
    if (!user) { setLoading(false); setError("Sua sessão não está disponível. Entre novamente."); return; }
    let active = true; setLoading(true); setError("");
    void refresh().catch((loadError) => { if (active) setError(friendlyProductivityError(loadError)); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [authLoading, refresh, user]);

  async function withSave(action: () => Promise<void>) {
    if (saving) return; setSaving(true); setError("");
    try { await action(); await refresh(); window.dispatchEvent(new CustomEvent("apex-productivity-changed")); }
    catch (saveError) { setError(friendlyProductivityError(saveError)); }
    finally { setSaving(false); }
  }

  if (loading) return <Card className="flex items-center gap-2 p-5 text-[10px] text-ink-muted"><LoaderCircle size={14} className="animate-spin text-accent" />Carregando Planejamento...</Card>;
  if (!user) return <Card className="p-5 text-[10px] text-red-300">{error}</Card>;

  return <div className="space-y-8">
    {error && <p className="flex items-center gap-2 rounded-control border border-red-400/20 bg-red-400/5 p-3 text-[9px] text-red-300"><AlertCircle size={13} />{error}</p>}
    {view === "agenda" && <AgendaSection habits={habits} plans={plans} tasks={tasks} dates={dates} saving={saving} onEditDay={setEditingDay} onNewTask={() => setTaskDraft(emptyTask())} onEditTask={(task) => setTaskDraft(taskToDraft(task))} onArchiveTask={(task) => void withSave(async () => { if (window.confirm(`Arquivar “${task.name}”?`)) await archiveTask(user.id, task.id); })} />}
    {view === "metas" && <GoalsSection goals={goals} habits={habits} onNew={() => setGoalDraft(emptyGoal())} onEdit={(goal) => setGoalDraft({ ...goal, id: goal.id })} onArchive={(goal) => void withSave(async () => { if (window.confirm(`Arquivar a meta “${goal.title}”?`)) await archiveGoal(user.id, goal.id); })} />}
    {view === "biblioteca" && <ReadingSection goals={goals} projects={projects} sessions={sessions} cycles={cycles} onNew={() => setBookDraft("new")} onEdit={setBookDraft} onStatus={(project, status) => void withSave(async () => { await saveReadingProject(user.id, { ...project, status, completedAt: status === "completed" ? (project.completedAt ?? isoDate(new Date())) : status === "active" ? undefined : project.completedAt }, project.id); })} onArchive={(project) => void withSave(async () => { if (window.confirm(`Arquivar “${project.title}”?`)) await archiveReadingProject(user.id, project.id); })} onNewCycle={() => setShowCycleForm(true)} />}

    {editingDay && <DayPlanModal date={editingDay} habits={habits} selectedIds={habits.filter((habit) => habitIsScheduled(habit, editingDay, plans)).map((habit) => habit.id)} hasOverride={plans.some((plan) => plan.date === editingDay)} saving={saving} onSave={(ids) => void withSave(async () => { await saveHabitDayPlan(editingDay, ids); setEditingDay(null); })} onReset={() => void withSave(async () => { await clearHabitDayPlan(user.id, editingDay); setEditingDay(null); })} onClose={() => setEditingDay(null)} />}
    {taskDraft && <TaskForm draft={taskDraft} setDraft={setTaskDraft} saving={saving} onSave={() => void withSave(async () => { await saveTask(user.id, taskDraft); setTaskDraft(null); })} onClose={() => setTaskDraft(null)} />}
    {goalDraft && <GoalForm draft={goalDraft} setDraft={setGoalDraft} habits={habits} templates={trainingTemplates} saving={saving} onSave={() => void withSave(async () => { await saveGoal(goalDraft); setGoalDraft(null); })} onClose={() => setGoalDraft(null)} />}
    {bookDraft && <div className="fixed inset-0 z-[110] flex items-end justify-center bg-black/75 p-4 backdrop-blur-sm sm:items-center"><div className="max-h-[95vh] w-full max-w-2xl overflow-y-auto"><BookForm initial={bookDraft === "new" ? undefined : bookDraft} goals={goals} cycles={cycles} onSave={(data) => void withSave(async () => { await saveReadingProject(user.id, data, bookDraft === "new" ? null : bookDraft.id); setBookDraft(null); })} onCancel={() => setBookDraft(null)} /></div></div>}
    {showCycleForm && <CycleForm saving={saving} onSave={(cycle) => void withSave(async () => { await saveReadingCycle(user.id, cycle); setShowCycleForm(false); })} onClose={() => setShowCycleForm(false)} />}
  </div>;
}

function AgendaSection({ habits, plans, tasks, dates, saving, onEditDay, onNewTask, onEditTask, onArchiveTask }: { habits: Habit[]; plans: HabitDayPlan[]; tasks: Task[]; dates: string[]; saving: boolean; onEditDay: (date: string) => void; onNewTask: () => void; onEditTask: (task: Task) => void; onArchiveTask: (task: Task) => void }) {
  const today = isoDate(new Date());
  return <><section><SectionHeader eyebrow="Rotina derivada das frequências" title="Semana atual" /><div className="space-y-2">{dates.map((date) => { const rows = habits.filter((habit) => habitIsScheduled(habit, date, plans)); const override = plans.some((plan) => plan.date === date); const dateObject = new Date(`${date}T12:00:00`); return <Card key={date} emphasis={date === today} className="p-4"><div className="flex items-center gap-3"><span className={`flex h-10 w-10 shrink-0 flex-col items-center justify-center rounded-control border ${date === today ? "border-line-accent bg-accent-subtle text-accent" : "border-line text-ink-muted"}`}><span className="text-[7px] uppercase">{DOW[dateObject.getDay()]}</span><span className="font-stat text-[11px]">{date.slice(8, 10)}</span></span><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-1.5">{rows.length ? rows.map((habit) => <span key={habit.id} className="flex items-center gap-1 rounded-full border px-2 py-1 text-[8px]" style={{ color: habit.color, borderColor: `${habit.color}35`, background: `${habit.color}10` }}><LucideIcon name={habit.lucideIcon} size={9} color={habit.color} />{habit.name}</span>) : <span className="text-[9px] text-ink-faint">Nenhum hábito planejado</span>}</div>{override && <p className="mt-2 text-[7px] font-semibold uppercase text-accent">Dia personalizado</p>}</div><button type="button" onClick={() => onEditDay(date)} className="flex h-9 w-9 items-center justify-center rounded-control border border-line text-ink-muted"><Pencil size={12} /></button></div></Card>; })}</div></section>
    <section><SectionHeader eyebrow="Tarefas e lembretes" title="Planejamento de tarefas" action={<button type="button" onClick={onNewTask} className="apex-button-primary"><Plus size={12} />Nova tarefa</button>} />{tasks.length === 0 ? <Card className="p-8 text-center text-[9px] text-ink-muted">Nenhuma tarefa planejada. A Captura rápida também salva tarefas aqui.</Card> : <div className="grid gap-3 lg:grid-cols-2">{tasks.map((task) => <Card key={task.id} className="p-4"><div className="flex items-start gap-3"><Clock3 size={14} className="mt-0.5 text-accent" /><div className="min-w-0 flex-1"><p className="text-[11px] font-semibold text-ink">{task.name}</p><p className="mt-1 text-[8px] text-ink-muted">{taskFrequencyLabel(task.frequency)}{task.date ? ` · ${task.date}` : ""}{task.time ? ` · ${task.time}` : ""}</p>{task.notes && <p className="mt-2 text-[8px] text-ink-faint">{task.notes}</p>}</div><div className="flex gap-1"><button type="button" onClick={() => onEditTask(task)} className="flex h-8 w-8 items-center justify-center rounded-control border border-line text-ink-muted"><Pencil size={11} /></button><button type="button" disabled={saving} onClick={() => onArchiveTask(task)} className="flex h-8 w-8 items-center justify-center rounded-control border border-line text-ink-muted hover:text-red-300"><Trash2 size={11} /></button></div></div></Card>)}</div>}</section></>;
}

function GoalsSection({ goals, habits, onNew, onEdit, onArchive }: { goals: Goal[]; habits: Habit[]; onNew: () => void; onEdit: (goal: Goal) => void; onArchive: (goal: Goal) => void }) {
  return <section><SectionHeader eyebrow="Criadas no Planejamento, acompanhadas no Progresso" title="Metas de longo prazo" action={<button type="button" onClick={onNew} className="apex-button-primary"><Plus size={12} />Nova meta</button>} />{goals.length === 0 ? <Card className="p-10 text-center"><Target size={22} className="mx-auto text-ink-faint" /><p className="mt-3 text-[12px] font-semibold text-ink-secondary">Nenhuma meta criada</p><p className="mt-2 text-[9px] text-ink-muted">Defina resultados mensuráveis e conecte hábitos ou fichas de treino.</p></Card> : <div className="grid gap-3 lg:grid-cols-2">{goals.map((goal) => { const progress = Math.max(0, Math.min(100, (goal.current / goal.target) * 100)); const linked = habits.filter((habit) => goal.linkedHabitIds.includes(habit.id)); return <Card key={goal.id} emphasis={goal.status === "completed"} className="p-4"><div className="flex items-start gap-3"><Target size={15} className="mt-0.5 text-accent" /><div className="min-w-0 flex-1"><p className="text-[12px] font-semibold text-ink">{goal.title}</p><p className="mt-1 font-stat text-[9px] text-ink-muted">{goal.current} → {goal.target} {goal.unit} · prazo {goal.targetDate}</p></div><button type="button" onClick={() => onEdit(goal)} className="flex h-8 w-8 items-center justify-center rounded-control border border-line text-ink-muted"><Pencil size={11} /></button><button type="button" onClick={() => onArchive(goal)} className="flex h-8 w-8 items-center justify-center rounded-control border border-line text-ink-muted hover:text-red-300"><Trash2 size={11} /></button></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-surface"><span className="block h-full rounded-full bg-accent" style={{ width: `${progress}%` }} /></div><div className="mt-3 flex flex-wrap gap-1.5">{linked.map((habit) => <span key={habit.id} className="rounded-full border px-2 py-1 text-[7px]" style={{ color: habit.color, borderColor: `${habit.color}35` }}>{habit.name}</span>)}{goal.linkedWorkoutTemplateIds.length > 0 && <span className="rounded-full border border-line px-2 py-1 text-[7px] text-ink-muted">{goal.linkedWorkoutTemplateIds.length} ficha(s)</span>}</div></Card>; })}</div>}</section>;
}

function ReadingSection({ goals, projects, sessions, cycles, onNew, onEdit, onStatus, onArchive, onNewCycle }: { goals: Goal[]; projects: ReadingProject[]; sessions: Awaited<ReturnType<typeof loadReadingData>>["sessions"]; cycles: ReadingCycle[]; onNew: () => void; onEdit: (project: ReadingProject) => void; onStatus: (project: ReadingProject, status: ReadingStatus) => void; onArchive: (project: ReadingProject) => void; onNewCycle: () => void }) {
  const readingGoals = goals.filter((goal) => goal.unit.toLocaleLowerCase("pt-BR").includes("livro") || projects.some((project) => project.linkedGoalId === goal.id));
  return <><section><SectionHeader eyebrow="Projetos reais de leitura" title="Biblioteca" action={<button type="button" onClick={onNew} className="apex-button-primary"><Plus size={12} />Novo livro</button>} />{readingGoals.map((goal) => <Card key={goal.id} className="mb-3 p-3"><div className="flex items-center justify-between"><p className="text-[10px] font-semibold text-ink-secondary">{goal.title}</p><span className="font-stat text-[9px] text-accent">{completedBooksForGoal(projects, goal.id)}/{goal.target} livros</span></div></Card>)}{projects.length === 0 ? <Card className="p-10 text-center"><p className="text-[12px] font-semibold text-ink-secondary">Nenhum livro cadastrado</p><p className="mt-2 text-[9px] text-ink-muted">A Biblioteca começa vazia e usa apenas seus registros.</p></Card> : <div className="grid gap-3 lg:grid-cols-2">{projects.map((project) => <BookCard key={project.id} book={project} sessions={sessions} mode="planning" onEdit={() => onEdit(project)} onDelete={() => onArchive(project)} onStatus={(status) => onStatus(project, status)} />)}</div>}</section>
    <section><SectionHeader eyebrow="Períodos de leitura" title="Ciclos" action={<button type="button" onClick={onNewCycle} className="apex-button-secondary"><Plus size={12} />Novo ciclo</button>} />{cycles.length === 0 ? <Card className="p-6 text-center text-[9px] text-ink-muted">Nenhum ciclo de leitura criado.</Card> : <div className="grid gap-3 lg:grid-cols-2">{cycles.map((cycle) => <Card key={cycle.id} className="p-4"><div className="flex items-center gap-3"><CalendarRange size={15} className="text-accent" /><div><p className="text-[11px] font-semibold text-ink">{cycle.label}</p><p className="mt-1 text-[8px] text-ink-muted">{cycle.startDate} → {cycle.endDate} · {completedBooksForCycle(projects, cycle)}/{cycle.targetBooks} livros</p></div></div></Card>)}</div>}</section></>;
}

function DayPlanModal({ date, habits, selectedIds, hasOverride, saving, onSave, onReset, onClose }: { date: string; habits: Habit[]; selectedIds: string[]; hasOverride: boolean; saving: boolean; onSave: (ids: string[]) => void; onReset: () => void; onClose: () => void }) {
  const [selected, setSelected] = useState(selectedIds);
  return <Modal title={`Rotina de ${FULL_DOW[new Date(`${date}T12:00:00`).getDay()]}`} subtitle={date} saving={saving} onClose={onClose}><div className="max-h-72 space-y-2 overflow-y-auto">{habits.map((habit) => { const active = selected.includes(habit.id); return <button key={habit.id} type="button" onClick={() => setSelected((value) => active ? value.filter((id) => id !== habit.id) : [...value, habit.id])} className="flex w-full items-center gap-3 rounded-control border p-3 text-left" style={{ borderColor: active ? habit.color : "var(--border-default)", background: active ? `${habit.color}10` : "transparent" }}><span className="flex h-6 w-6 items-center justify-center rounded border" style={{ background: active ? habit.color : "transparent", borderColor: active ? habit.color : "var(--border-default)" }}>{active && <Check size={11} color="#111" />}</span><LucideIcon name={habit.lucideIcon} size={13} color={active ? habit.color : "var(--text-muted)"} /><span className="flex-1 text-[10px] text-ink-secondary">{habit.name}</span><span className="font-stat text-[8px] text-ink-muted">{habit.time}</span></button>; })}</div><div className="mt-4 flex flex-wrap justify-end gap-2">{hasOverride && <button type="button" onClick={onReset} disabled={saving} className="apex-button-secondary">Usar frequência padrão</button>}<button type="button" onClick={() => onSave(selected)} disabled={saving} className="apex-button-primary">Salvar este dia</button></div></Modal>;
}

function TaskForm({ draft, setDraft, saving, onSave, onClose }: { draft: TaskDraft; setDraft: (draft: TaskDraft) => void; saving: boolean; onSave: () => void; onClose: () => void }) {
  return <Modal title={draft.id ? "Editar tarefa" : "Nova tarefa"} saving={saving} onClose={onClose}><div className="space-y-3"><Field label="Tarefa"><input value={draft.name} maxLength={240} onChange={(event) => setDraft({ ...draft, name: event.target.value })} className="apex-input" /></Field><div className="grid grid-cols-2 gap-3"><Field label="Horário opcional"><input type="time" value={draft.time} onChange={(event) => setDraft({ ...draft, time: event.target.value })} className="apex-input" /></Field><Field label="Frequência"><select value={draft.frequency.type} onChange={(event) => { const type = event.target.value as TaskFrequency["type"]; const frequency: TaskFrequency = type === "once" ? { type: "once" } : type === "daily" ? { type: "daily" } : type === "xPerWeek" ? { type: "xPerWeek", times: 1 } : { type: "specificDays", days: [1] }; setDraft({ ...draft, frequency }); }} className="apex-input"><option value="once">Uma vez</option><option value="daily">Diária</option><option value="xPerWeek">X vezes/semana</option><option value="specificDays">Dias fixos</option></select></Field></div>{draft.frequency.type === "once" && <Field label="Data"><input type="date" value={draft.date} onChange={(event) => setDraft({ ...draft, date: event.target.value })} className="apex-input" /></Field>}{draft.frequency.type === "xPerWeek" && <Field label="Vezes por semana"><input type="number" min={1} max={7} value={draft.frequency.times} onChange={(event) => setDraft({ ...draft, frequency: { type: "xPerWeek", times: Math.min(7, Math.max(1, Number(event.target.value))) } })} className="apex-input" /></Field>}{draft.frequency.type === "specificDays" && <div className="flex flex-wrap gap-2">{DOW.map((day, index) => { const active = draft.frequency.type === "specificDays" && draft.frequency.days.includes(index); return <button key={day} type="button" onClick={() => { if (draft.frequency.type !== "specificDays") return; setDraft({ ...draft, frequency: { type: "specificDays", days: active ? draft.frequency.days.filter((value) => value !== index) : [...draft.frequency.days, index].sort() } }); }} className={`rounded-control border px-3 py-2 text-[9px] ${active ? "border-line-accent bg-accent-subtle text-accent" : "border-line text-ink-muted"}`}>{day}</button>; })}</div>}<Field label="Observações"><textarea value={draft.notes} maxLength={1000} onChange={(event) => setDraft({ ...draft, notes: event.target.value })} rows={3} className="apex-input min-h-20 resize-y" /></Field></div><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={onClose} className="apex-button-secondary">Cancelar</button><button type="button" disabled={saving || !draft.name.trim() || (draft.frequency.type === "once" && !draft.date)} onClick={onSave} className="apex-button-primary">Salvar tarefa</button></div></Modal>;
}

function GoalForm({ draft, setDraft, habits, templates, saving, onSave, onClose }: { draft: GoalDraft; setDraft: (draft: GoalDraft) => void; habits: Habit[]; templates: TrainingTemplate[]; saving: boolean; onSave: () => void; onClose: () => void }) {
  return <Modal title={draft.id ? "Editar meta" : "Nova meta"} saving={saving} onClose={onClose}><div className="space-y-3"><Field label="Título"><input value={draft.title} maxLength={180} onChange={(event) => setDraft({ ...draft, title: event.target.value })} className="apex-input" /></Field><div className="grid grid-cols-2 gap-3"><Field label="Atual"><input type="number" step="0.01" value={draft.current} onChange={(event) => setDraft({ ...draft, current: Number(event.target.value) })} className="apex-input" /></Field><Field label="Meta"><input type="number" min={0.01} step="0.01" value={draft.target} onChange={(event) => setDraft({ ...draft, target: Number(event.target.value) })} className="apex-input" /></Field><Field label="Unidade"><input value={draft.unit} maxLength={40} onChange={(event) => setDraft({ ...draft, unit: event.target.value })} className="apex-input" placeholder="kg, km, livros..." /></Field><Field label="Prazo"><input type="date" value={draft.targetDate} onChange={(event) => setDraft({ ...draft, targetDate: event.target.value })} className="apex-input" /></Field></div><Field label="Status"><select value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as Goal["status"] })} className="apex-input"><option value="active">Ativa</option><option value="paused">Pausada</option><option value="completed">Concluída</option></select></Field><div><p className="apex-kicker mb-2">Hábitos vinculados</p><div className="flex flex-wrap gap-2">{habits.map((habit) => { const active = draft.linkedHabitIds.includes(habit.id); return <button key={habit.id} type="button" onClick={() => setDraft({ ...draft, linkedHabitIds: active ? draft.linkedHabitIds.filter((id) => id !== habit.id) : [...draft.linkedHabitIds, habit.id] })} className="rounded-full border px-2.5 py-1.5 text-[8px]" style={{ color: active ? habit.color : "var(--text-muted)", borderColor: active ? habit.color : "var(--border-default)" }}>{habit.name}</button>; })}</div></div><div><p className="apex-kicker mb-2">Fichas de treino vinculadas</p><div className="flex flex-wrap gap-2">{templates.map((template) => { const active = draft.linkedWorkoutTemplateIds.includes(template.id); return <button key={template.id} type="button" onClick={() => setDraft({ ...draft, linkedWorkoutTemplateIds: active ? draft.linkedWorkoutTemplateIds.filter((id) => id !== template.id) : [...draft.linkedWorkoutTemplateIds, template.id] })} className={`rounded-full border px-2.5 py-1.5 text-[8px] ${active ? "border-line-accent text-accent" : "border-line text-ink-muted"}`}>{template.name}</button>; })}</div></div></div><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={onClose} className="apex-button-secondary">Cancelar</button><button type="button" disabled={saving || !draft.title.trim() || !draft.targetDate || draft.target <= 0} onClick={onSave} className="apex-button-primary">Salvar meta</button></div></Modal>;
}

function CycleForm({ saving, onSave, onClose }: { saving: boolean; onSave: (cycle: Omit<ReadingCycle, "id">) => void; onClose: () => void }) {
  const [label, setLabel] = useState(""); const [startDate, setStartDate] = useState(isoDate(new Date())); const [endDate, setEndDate] = useState(isoDate(new Date())); const [targetBooks, setTargetBooks] = useState(1);
  return <Modal title="Novo ciclo de leitura" saving={saving} onClose={onClose}><div className="space-y-3"><Field label="Nome"><input value={label} onChange={(event) => setLabel(event.target.value)} className="apex-input" placeholder="Ex.: 3º trimestre" /></Field><div className="grid grid-cols-2 gap-3"><Field label="Início"><input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} className="apex-input" /></Field><Field label="Fim"><input type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)} className="apex-input" /></Field></div><Field label="Livros-meta"><input type="number" min={1} max={1000} value={targetBooks} onChange={(event) => setTargetBooks(Number(event.target.value))} className="apex-input" /></Field></div><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={onClose} className="apex-button-secondary">Cancelar</button><button type="button" disabled={saving || !label.trim() || endDate < startDate || targetBooks < 1} onClick={() => onSave({ label: label.trim(), startDate, endDate, targetBooks })} className="apex-button-primary">Salvar ciclo</button></div></Modal>;
}

function Modal({ title, subtitle, saving, onClose, children }: { title: string; subtitle?: string; saving: boolean; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-[110] flex items-end justify-center bg-black/75 backdrop-blur-sm sm:items-center sm:p-5"><Card emphasis className="max-h-[95vh] w-full overflow-y-auto rounded-b-none p-4 sm:max-w-xl sm:rounded-panel"><div className="mb-4 flex items-start justify-between"><div><p className="apex-kicker">Planejamento persistente</p><h3 className="mt-2 text-[15px] font-semibold text-ink">{title}</h3>{subtitle && <p className="mt-1 font-stat text-[8px] text-ink-muted">{subtitle}</p>}</div><button type="button" onClick={onClose} disabled={saving} className="flex h-9 w-9 items-center justify-center rounded-control border border-line text-ink-muted"><X size={14} /></button></div>{children}</Card></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-[8px] font-semibold uppercase tracking-wide text-ink-faint">{label}</span>{children}</label>; }
function emptyTask(): TaskDraft { return { id: null, name: "", time: "", frequency: { type: "once" }, date: isoDate(new Date()), notes: "" }; }
function taskToDraft(task: Task): TaskDraft { return { id: task.id, name: task.name, time: task.time ?? "", frequency: task.frequency, date: task.date ?? isoDate(new Date()), notes: task.notes }; }
function emptyGoal(): GoalDraft { return { id: null, title: "", targetDate: isoDate(new Date()), current: 0, target: 1, unit: "", status: "active", linkedHabitIds: [], linkedWorkoutTemplateIds: [] }; }
function taskFrequencyLabel(frequency: TaskFrequency) { if (frequency.type === "once") return "Uma vez"; if (frequency.type === "daily") return "Diária"; if (frequency.type === "xPerWeek") return `${frequency.times}x/semana`; return frequency.days.map((day) => DOW[day]).join(" · "); }
